import { test, expect } from '@playwright/test'
import { deadlineInfo } from '../src/utils/deadline.js'

const password = 'demo1234'
const tasksPath = (workspaceId, id = '') => `/api/tasks.php?workspace_id=${workspaceId}${id ? `&id=${id}` : ''}`
const region = (page, status) => page.getByRole('region', { name: status, exact: true })

async function register(api, email, name = 'Anggota Tim') {
  const response = await api.post('/api/auth.php?action=register', { data: { name, email, password } })
  expect(response.status()).toBe(201)
  return (await response.json()).user
}
async function createWorkspace(api, name = 'Project Bersama') {
  const response = await api.post('/api/workspaces.php', { data: { name, description: 'Workspace pengujian kolaborasi.' } })
  expect(response.status()).toBe(201)
  return (await response.json()).workspace
}
async function otherAccount(playwright, baseURL, email, name) {
  const api = await playwright.request.newContext({ baseURL })
  const user = await register(api, email, name)
  return { api, user }
}
async function addTask(page, title) {
  await page.getByRole('button', { name: 'Tambah task', exact: true }).first().click()
  await page.getByLabel('Judul task').fill(title)
  await page.getByLabel('Deskripsi (opsional)').fill('Task kolaborasi yang tersimpan di database.')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

test('register pertama mendapatkan task lama; session bertahan, logout dan login berfungsi', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali.' })).toBeVisible()
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Daftar sekarang' }).click()
  await page.getByLabel('Nama lengkap').fill('Pemilik Pertama')
  await page.getByLabel('Email', { exact: true }).fill('owner-first@example.com')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Konfirmasi password').fill(password)
  await page.getByRole('button', { name: 'Buat akun', exact: true }).click()
  const workspace = page.getByRole('article', { name: 'TaskFlow Hackathon', exact: true })
  await expect(workspace).toContainText('Owner')
  await page.screenshot({ path: 'test-results/workspaces-desktop.png', fullPage: true })
  await workspace.getByRole('button', { name: 'Buka workspace' }).click()
  await expect(page.getByRole('article')).toHaveCount(7)
  await page.screenshot({ path: 'test-results/board-desktop.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(7)
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali.' })).toBeVisible()
  expect((await page.request.get(tasksPath('00000000-0000-4000-8000-000000000000'))).status()).toBe(401)
  await page.getByLabel('Email', { exact: true }).fill('owner-first@example.com')
  await page.getByLabel('Password', { exact: true }).fill('salah123')
  await page.getByRole('button', { name: 'Masuk', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Email atau password salah.')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Masuk', exact: true }).click()
  await expect(workspace).toBeVisible()
})

test('buat workspace, tambah/pindah/drag/hapus task, dan task terpisah antar workspace', async ({ page }) => {
  await register(page.request, 'creator@example.com', 'Pembuat Workspace')
  await page.goto('/')
  await page.getByRole('button', { name: 'Buat workspace', exact: true }).click()
  await page.getByLabel('Nama workspace').fill('Produk Tim')
  await page.getByLabel('Deskripsi (opsional)').fill('Project pertama tim.')
  await page.getByRole('dialog').getByRole('button', { name: 'Buat workspace', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Produk Tim.' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(0)
  await addTask(page, 'Task Project A')
  const task = page.getByRole('article', { name: 'Task Project A', exact: true })
  await page.reload()
  await expect(task).toBeVisible()
  await page.getByLabel('Status task Task Project A').selectOption('in_progress')
  await expect(region(page, 'In Progress').getByRole('article', { name: 'Task Project A' })).toBeVisible()
  await task.dragTo(region(page, 'Done'))
  await expect(region(page, 'Done').getByRole('article', { name: 'Task Project A' })).toBeVisible()
  await page.reload()
  await expect(region(page, 'Done').getByRole('article', { name: 'Task Project A' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Cari task' }).fill('kolaborasi')
  await expect(task).toBeVisible()
  await page.getByRole('button', { name: 'Bersihkan pencarian' }).click()
  await page.getByLabel('Filter status').selectOption('todo')
  await expect(page.getByRole('article')).toHaveCount(0)
  await page.getByLabel('Filter status').selectOption('all')
  await page.getByRole('button', { name: 'Semua workspace' }).click()
  await expect(page.getByRole('article', { name: 'Produk Tim' })).toContainText('1 task')
  const second = await createWorkspace(page.request, 'Project B')
  await page.goto(`/#workspace=${second.id}`)
  await expect(page.getByRole('heading', { name: 'Project B.' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(0)
  const workspaces = (await (await page.request.get('/api/workspaces.php')).json()).workspaces
  const first = workspaces.find((item) => item.name === 'Produk Tim')
  await page.goto(`/#workspace=${first.id}`)
  await expect(task).toBeVisible()
  await page.getByRole('button', { name: 'Hapus task Task Project A' }).click()
  await expect(task).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(0)
})

test('gabung dengan kode, kode salah ditolak, dan member dapat menambah task bersama', async ({ page, playwright, baseURL }) => {
  const { api: owner } = await otherAccount(playwright, baseURL, 'join-owner@example.com', 'Owner Kolaborasi')
  try {
    const workspace = await createWorkspace(owner, 'Tim Kolaborasi')
    const member = await register(page.request, 'joining-member@example.com', 'Member Kolaborasi')
    await page.goto('/')
    await page.getByRole('button', { name: 'Gabung workspace', exact: true }).click()
    await page.getByLabel('Kode undangan').fill('INVALID0')
    await page.getByRole('dialog').getByRole('button', { name: 'Gabung workspace', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Kode undangan tidak ditemukan.')
    await page.getByLabel('Kode undangan').fill(workspace.invite_code.toLowerCase())
    await page.getByRole('dialog').getByRole('button', { name: 'Gabung workspace', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Tim Kolaborasi.' })).toBeVisible()
    await addTask(page, 'Task dari member')
    const task = (await (await owner.get(tasksPath(workspace.id))).json()).tasks[0]
    expect(task.title).toBe('Task dari member')
    expect(task.created_by).toBe(member.id)
    expect((await page.request.post('/api/workspaces.php?action=join', { data: { invite_code: workspace.invite_code } })).status()).toBe(200)
    expect((await (await owner.get(`/api/workspaces.php?id=${workspace.id}&action=members`)).json()).members).toHaveLength(2)
    await page.getByRole('button', { name: 'Anggota & pengaturan' }).click()
    await expect(page.getByRole('dialog')).toContainText('Member Kolaborasi')
    await page.screenshot({ path: 'test-results/members-desktop.png', fullPage: true })
    await expect(page.getByRole('dialog')).toContainText('Owner Kolaborasi')
    await expect(page.getByRole('button', { name: 'Simpan perubahan' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Buat kode baru' })).toHaveCount(0)
  } finally { await owner.dispose() }
})

test('owner dapat mengubah workspace, mengganti kode, dan mengeluarkan anggota', async ({ page, playwright, baseURL }) => {
  const user = await register(page.request, 'settings-owner@example.com', 'Owner Pengaturan')
  const workspace = await createWorkspace(page.request, 'Workspace Pengaturan')
  const { api: member, user: memberUser } = await otherAccount(playwright, baseURL, 'settings-member@example.com', 'Member Pengaturan')
  const { api: outsider } = await otherAccount(playwright, baseURL, 'settings-outsider@example.com', 'Teman Baru')
  try {
    await member.post('/api/workspaces.php?action=join', { data: { invite_code: workspace.invite_code } })
    expect((await member.patch(`/api/workspaces.php?id=${workspace.id}`, { data: { name: 'Tidak boleh', description: '' } })).status()).toBe(403)
    expect((await member.delete(`/api/workspaces.php?id=${workspace.id}&action=member&user_id=${user.id}`)).status()).toBe(403)
    await page.goto(`/#workspace=${workspace.id}`)
    await page.getByRole('button', { name: 'Anggota & pengaturan' }).click()
    await page.getByLabel('Nama workspace').fill('Nama Workspace Baru')
    await page.getByLabel('Deskripsi workspace').fill('Deskripsi yang diperbarui.')
    await page.getByRole('button', { name: 'Simpan perubahan' }).click()
    await expect(page.getByRole('dialog')).toContainText('Workspace berhasil diperbarui.')
    await page.getByRole('button', { name: 'Buat kode baru' }).click()
    await expect(page.getByTestId('invite-code')).not.toHaveText(workspace.invite_code)
    const code = await page.getByTestId('invite-code').innerText()
    expect((await outsider.post('/api/workspaces.php?action=join', { data: { invite_code: workspace.invite_code } })).status()).toBe(404)
    expect((await outsider.post('/api/workspaces.php?action=join', { data: { invite_code: code } })).status()).toBe(200)
    await page.getByRole('button', { name: 'Keluarkan Member Pengaturan' }).click()
    await expect(page.getByRole('dialog')).toContainText('Anggota dikeluarkan')
    expect((await member.get(tasksPath(workspace.id))).status()).toBe(403)
    expect((await page.request.delete(`/api/workspaces.php?id=${workspace.id}&action=member&user_id=${user.id}`)).status()).toBe(422)
    const remaining = (await (await page.request.get(`/api/workspaces.php?id=${workspace.id}&action=members`)).json()).members
    expect(remaining.some((item) => item.id === memberUser.id)).toBe(false)
    await page.getByRole('button', { name: 'Tutup dialog' }).click()
    await expect(page.getByRole('heading', { name: 'Nama Workspace Baru.' })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Nama Workspace Baru.' })).toBeVisible()
  } finally { await member.dispose(); await outsider.dispose() }
})

test('API membatasi akses workspace dan menolak manipulasi ID task antar workspace', async ({ page, playwright, baseURL }) => {
  const { api: owner } = await otherAccount(playwright, baseURL, 'isolation-owner@example.com', 'Owner A')
  try {
    expect((await page.request.get('/api/workspaces.php')).status()).toBe(401)
    expect((await page.request.post('/api/tasks.php', { data: { title: 'Tanpa login' } })).status()).toBe(401)
    const first = await createWorkspace(owner, 'Workspace Rahasia A')
    const task = (await (await owner.post(tasksPath(first.id), { data: { title: 'Task privat', status: 'todo' } })).json()).task
    await register(page.request, 'isolation-outsider@example.com', 'Owner B')
    const second = await createWorkspace(page.request, 'Workspace B')
    expect((await page.request.get(tasksPath(first.id))).status()).toBe(403)
    expect((await page.request.post(tasksPath(first.id), { data: { title: 'Task ilegal' } })).status()).toBe(403)
    expect((await page.request.patch(tasksPath(second.id, task.id), { data: { status: 'done' } })).status()).toBe(404)
    expect((await page.request.delete(tasksPath(second.id, task.id))).status()).toBe(404)
    const unchanged = (await (await owner.get(tasksPath(first.id))).json()).tasks[0]
    expect(unchanged.status).toBe('todo')
    expect((await page.request.post('/api/auth.php?action=register', { data: { name: 'Duplikat', email: 'isolation-outsider@example.com', password } })).status()).toBe(409)
  } finally { await owner.dispose() }
})

test('layar kecil, validasi form, dan navigasi keyboard modal tetap berfungsi', async ({ page }) => {
  await page.goto('/')
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/login-mobile.png', fullPage: true })
  await register(page.request, 'mobile@example.com', 'User Mobile')
  await page.reload()
  await page.getByRole('button', { name: 'Buat workspace', exact: true }).click()
  await expect(page.getByLabel('Nama workspace')).toBeFocused()
  await page.getByRole('dialog').getByRole('button', { name: 'Buat workspace', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Tutup dialog' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const workspace = await createWorkspace(page.request, 'Workspace Mobile')
  await page.goto(`/#workspace=${workspace.id}`)
  await page.getByRole('button', { name: 'Tambah task', exact: true }).first().click()
  await page.getByLabel('Judul task').fill('   ')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await expect(page.getByText('Judul task perlu diisi.')).toBeVisible()
  await page.getByLabel('Judul task').fill('Task Mobile')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await page.getByLabel('Status task Task Mobile').selectOption('done')
  await expect(region(page, 'Done').getByRole('article', { name: 'Task Mobile' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('penyimpanan gagal mempertahankan form; session berakhir kembali ke login', async ({ page }) => {
  await register(page.request, 'failure@example.com', 'Uji Kegagalan')
  const workspace = await createWorkspace(page.request, 'Workspace Kegagalan')
  await page.goto(`/#workspace=${workspace.id}`)
  await page.route('**/api/tasks.php*', (route) => route.request().method() === 'POST'
    ? route.fulfill({ status: 500, json: { error: 'Penyimpanan sedang gagal.' } }) : route.continue())
  await page.getByRole('button', { name: 'Tambah task', exact: true }).first().click()
  await page.getByLabel('Judul task').fill('Task belum tersimpan')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Penyimpanan sedang gagal.')
  await expect(page.getByLabel('Judul task')).toHaveValue('Task belum tersimpan')
  await expect(page.getByRole('article')).toHaveCount(0)
  await page.unroute('**/api/tasks.php*')
  await page.request.post('/api/auth.php?action=logout')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali.' })).toBeVisible()
})


test('kolom custom: warna, persistensi, pindah task, dan hapus hanya pada workspace aktif', async ({ page }) => {
  await register(page.request, 'columns@example.com')
  const a = await createWorkspace(page.request, 'Kolom Tim A')
  const b = await createWorkspace(page.request, 'Kolom Tim B')
  const path = (workspace, id = '') => `/api/columns.php?workspace_id=${workspace.id}${id ? `&id=${id}` : ''}`
  await page.goto(`/#workspace=${a.id}`)
  await page.getByRole('button', { name: 'Tambah kolom baru' }).click()
  await page.getByLabel('Nama kolom').fill('In Review')
  await page.getByLabel('Deskripsi (opsional)').fill('Peninjauan bersama tim')
  await page.getByRole('button', { name: 'Rose', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rose', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Buat kolom', exact: true }).click()
  const review = region(page, 'In Review')
  await expect(review).toHaveClass(/column-rose/)
  await expect(review).toContainText('Peninjauan bersama tim')
  await page.getByRole('button', { name: 'Tambah task ke In Review' }).click()
  await page.getByLabel('Judul task').fill('Review Produk')
  await expect(page.getByLabel('Status awal')).toHaveValue('in_review')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  await expect(review.getByRole('article', { name: 'Review Produk' })).toBeVisible()
  await page.getByLabel('Status task Review Produk').selectOption('todo')
  await expect(region(page, 'To Do').getByRole('article', { name: 'Review Produk' })).toBeVisible()
  await page.getByRole('article', { name: 'Review Produk' }).dragTo(review)
  await expect(review.getByRole('article', { name: 'Review Produk' })).toBeVisible()
  await page.reload()
  await expect(review.getByRole('article', { name: 'Review Produk' })).toBeVisible()
  await page.getByLabel('Filter status').selectOption('in_review')
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/custom-columns-desktop.png', fullPage: true })
  const otherColumn = await page.request.post(path(b), { data: { label: 'In Review', description: '', color: 'teal' } })
  expect(otherColumn.status()).toBe(201)
  expect((await otherColumn.json()).column.id).toBe('in_review')
  await page.request.post(tasksPath(b.id), { data: { title: 'Review B', description: '', status: 'in_review' } })
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Hapus kolom In Review' }).click()
  await expect(review).toHaveCount(0)
  await expect(region(page, 'To Do').getByRole('article', { name: 'Review Produk' })).toBeVisible()
  expect((await (await page.request.get(tasksPath(b.id))).json()).tasks[0].status).toBe('in_review')
  expect((await (await page.request.get(path(b))).json()).columns.find((column) => column.id === 'in_review').color).toBe('teal')
  await page.reload()
  await expect(review).toHaveCount(0)
  await expect(region(page, 'To Do').getByRole('article', { name: 'Review Produk' })).toBeVisible()
})

test('API kolom memeriksa anggota, validasi status, kolom utama, dan kegagalan simpan', async ({ page, playwright, baseURL }) => {
  await register(page.request, 'columns-owner@example.com')
  const workspace = await createWorkspace(page.request, 'Tim Validasi Kolom')
  const path = `/api/columns.php?workspace_id=${workspace.id}`
  const outsider = await playwright.request.newContext({ baseURL })
  try {
    expect((await outsider.get(path)).status()).toBe(401)
    await register(outsider, 'columns-outsider@example.com')
    expect((await outsider.get(path)).status()).toBe(403)
    expect((await outsider.post(path, { data: { label: 'Rahasia', color: 'sky' } })).status()).toBe(403)
    await outsider.post('/api/workspaces.php?action=join', { data: { invite_code: workspace.invite_code } })
    expect((await outsider.post(path, { data: { label: 'QA', description: '', color: 'sky' } })).status()).toBe(201)
    expect((await outsider.post(path, { data: { label: 'QA', description: '', color: 'sky' } })).status()).toBe(201)
    const columns = (await (await outsider.get(path)).json()).columns
    expect(new Set(columns.map((column) => column.id)).size).toBe(5)
    expect((await outsider.delete(`${path}&id=todo`)).status()).toBe(422)
    expect((await outsider.post(path, { data: { label: 'Invalid', description: '', color: 'invalid' } })).status()).toBe(422)
    expect((await outsider.post(tasksPath(workspace.id), { data: { title: 'Invalid', description: '', status: 'missing' } })).status()).toBe(422)
    const own = await createWorkspace(outsider, 'Workspace Terpisah')
    expect((await outsider.post(tasksPath(own.id), { data: { title: 'Invalid', description: '', status: 'qa' } })).status()).toBe(422)
    expect((await outsider.delete(`${path}&id=missing`)).status()).toBe(404)
  } finally { await outsider.dispose() }
  await page.goto(`/#workspace=${workspace.id}`)
  await page.route('**/api/columns.php*', (route) => route.request().method() === 'POST'
    ? route.fulfill({ status: 500, json: { error: 'Kolom gagal disimpan.' } }) : route.continue())
  await page.getByRole('button', { name: 'Tambah kolom baru' }).click()
  await page.getByLabel('Nama kolom').fill('Belum Disimpan')
  await page.getByRole('button', { name: 'Buat kolom', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Kolom gagal disimpan.')
  await expect(page.getByLabel('Nama kolom')).toHaveValue('Belum Disimpan')
  await expect(region(page, 'Belum Disimpan')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
})


test('penanda tanggal WIB, batas segera, dan Done', () => {
  const now = new Date('2026-10-03T18:00:00Z')
  expect(deadlineInfo(null, 'todo', now)).toBeNull()
  for (const [date, label] of [['2026-10-03', 'Terlambat'], ['2026-10-04', 'Hari ini'], ['2026-10-05', 'Segera'], ['2026-10-06', 'Segera'], ['2026-10-07', 'Deadline']]) {
    expect(deadlineInfo(date, 'todo', now).label).toBe(label)
  }
  expect(deadlineInfo('2026-10-03', 'done', now).label).toBe('Selesai')
})

test('deadline tambah, ubah, hapus, persistensi dan Done', async ({ page }) => {
  await register(page.request, 'deadline@example.com')
  const workspace = await createWorkspace(page.request, 'Tim Deadline')
  await page.goto(`/#workspace=${workspace.id}`)
  await page.getByRole('button', { name: 'Tambah task', exact: true }).first().click()
  await page.getByLabel('Judul task').fill('Task Deadline')
  await page.getByLabel('Deadline (opsional)').fill('2020-01-01')
  await page.getByRole('button', { name: 'Buat task', exact: true }).click()
  const card = page.getByRole('article', { name: 'Task Deadline', exact: true })
  await expect(card).toContainText('Terlambat')
  await page.reload()
  await expect(card).toContainText('Terlambat')
  await card.getByLabel('Status task Task Deadline').selectOption('done')
  await expect(card).toContainText('Selesai')
  await expect(card).not.toContainText('Terlambat')
  await card.getByLabel('Status task Task Deadline').selectOption('todo')
  await expect(card).toContainText('Terlambat')
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
  await card.getByRole('button', { name: 'Ubah deadline Task Deadline' }).click()
  await card.getByLabel('Deadline Task Deadline', { exact: true }).fill(today)
  await card.getByRole('button', { name: 'Simpan deadline' }).click()
  await expect(card).toContainText('Hari ini')
  await page.reload()
  await expect(card).toContainText('Hari ini')
  await card.getByRole('button', { name: 'Ubah deadline Task Deadline' }).click()
  await card.getByRole('button', { name: 'Hapus deadline' }).click()
  await expect(card.getByRole('button', { name: 'Tambah deadline Task Deadline' })).toBeVisible()
  await page.reload()
  await expect(card.getByRole('button', { name: 'Tambah deadline Task Deadline' })).toBeVisible()
  const tasks = (await (await page.request.get(tasksPath(workspace.id))).json()).tasks
  expect(tasks[0].deadline).toBeNull()
  expect(tasks[0].status).toBe('todo')
  await card.getByRole('button', { name: 'Tambah deadline Task Deadline' }).click()
  await card.getByLabel('Deadline Task Deadline', { exact: true }).fill('2030-01-01')
  await card.getByRole('button', { name: 'Simpan deadline' }).click()
  await expect(card).toContainText('1 Jan 2030')
  await page.screenshot({ path: 'test-results/deadline-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/deadline-mobile.png', fullPage: true })
})

test('validasi API deadline, isolasi workspace, dan kegagalan simpan', async ({ page }) => {
  await register(page.request, 'deadline-validation@example.com')
  const workspace = await createWorkspace(page.request, 'Validasi Deadline')
  for (const deadline of ['2026-02-30', '03-10-2026', '2026-10-03T12:00:00Z', 123, '0000-01-01']) {
    expect((await page.request.post(tasksPath(workspace.id), { data: { title: 'Invalid', description: '', deadline } })).status()).toBe(422)
  }
  const response = await page.request.post(tasksPath(workspace.id), { data: { title: 'Deadline API', description: '', deadline: '2028-02-29' } })
  expect(response.status()).toBe(201)
  const task = (await response.json()).task
  const other = await createWorkspace(page.request, 'Deadline Workspace Lain')
  expect((await page.request.patch(tasksPath(other.id, task.id), { data: { deadline: null } })).status()).toBe(404)
  expect((await page.request.patch(tasksPath(workspace.id, task.id), { data: { deadline: '2027-02-29' } })).status()).toBe(422)
  expect((await page.request.patch(tasksPath(workspace.id, task.id), { data: { deadline: '2031-01-01', status: 'done' } })).status()).toBe(200)
  const saved = (await (await page.request.get(tasksPath(workspace.id))).json()).tasks[0]
  expect(saved.deadline).toBe('2031-01-01')
  expect(saved.status).toBe('done')
  await page.goto(`/#workspace=${workspace.id}`)
  const card = page.getByRole('article', { name: 'Deadline API', exact: true })
  await card.getByRole('button', { name: 'Ubah deadline Deadline API' }).click()
  await card.getByLabel('Deadline Deadline API', { exact: true }).fill('2032-01-01')
  await page.route('**/api/tasks.php*', (route) => route.request().method() === 'PATCH'
    ? route.fulfill({ status: 500, json: { error: 'Deadline gagal disimpan.' } }) : route.continue())
  await card.getByRole('button', { name: 'Simpan deadline' }).click()
  await expect(page.getByRole('alert')).toContainText('Deadline gagal disimpan.')
  await expect(card.getByLabel('Deadline Deadline API', { exact: true })).toHaveValue('2032-01-01')
  expect((await (await page.request.get(tasksPath(workspace.id))).json()).tasks[0].deadline).toBe('2031-01-01')
  await card.getByRole('button', { name: 'Batal', exact: true }).click()
  await expect(card).toContainText('1 Jan 2031')
})
